myuser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.StudentListView.as_view(), name='student_changelist'),
    path('add/', views.StudentCreateView.as_view(), name='student_add'),
    path('<int:pk>/', views.StudentUpdateView.as_view(), name='student_change'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),
   ]

user/models.py
from django.db import models

# Create your models here.
class College(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Branch(models.Model):
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    college = models.ForeignKey(College, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name 

user/forms.py
from django import forms
from .models import Student, Branch

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'birthdate', 'college','branch')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'college' in self.data:
            try:
                college_id = int(self.data.get('college'))
                self.fields['branch'].queryset = Branch.objects.filter(college_id=college_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.college.branch_set.order_by('name')

user/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Student, Branch
from .forms import StudentForm
from django.shortcuts import render

class StudentListView(ListView):
    model = Student
    form_class = StudentForm
    context_object_name = 'students'

class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('student_changelist')

class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm  
    success_url = reverse_lazy('student_changelist')

def load_branches(request):
    college_id = request.GET.get('college')
    branches = Branch.objects.filter(college_id=college_id).order_by('name')
    return render(request, 'user/branch_dropdown_list_options.html', {'branches': branches})

templates/base.html
{% load static %}
<!doctype html>
<meta charset="utf-8">
    <title>{% block title %}Student Database{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  <head>
    
  </head>
  <body>
    <h1>Student Database</h1>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>

user/templates/user/branch_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

user/templates/user/student_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Student Form</h2>

  <form method="post" id="studentForm" data-branches-url="{% url 'ajax_load_branches' %}" novalidate>
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'student_changelist' %}">Nevermind</a>
  </form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_college").change(function () {
      var url = $("#studentForm").attr("data-branches-url");  
      var collegeId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'college': collegeId       
        },
        success: function (data) {  
          $("#id_branch").html(data);  
        }
      });

    });
  </script>


{% endblock %}

user/templates/user/student_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}
  <h2>Human Resources Module » People Management</h2>

  <p>
    <a href="{% url 'student_add' %}">Add Student</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>College</th>
        <th>Branch</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr>
          <td><a href="{% url 'student_change' student.pk %}">{{ student.name }}</a></td>
          <td>{{ student.birthdate }}</td>
          <td>{{ student.college.name }}</td>
          <td>{{ student.branch.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'student_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}